name: graphlib_dot
version: 0.0.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A DOT language parser / writer for graphlib.
dependencies:
  graphlib:
    path: ../graphlib
  unittest: any
